Update terraform-ci-cd.yml

diff --git a/.github/workflows/terraform-ci-cd.yml b/.github/workflows/terraform-ci-cd.yml
--- a/.github/workflows/terraform-ci-cd.yml
+++ b/.github/workflows/terraform-ci-cd.yml
@@ -35,7 +35,13 @@ jobs:
 
       - name: Install TFLint
         run: |
-          curl -L "$(curl -s https://api.github.com/repos/terraform-linters/tflint/releases/latest | grep -o -E "https://.+?_Linux_x86_64.zip")" -o tflint.zip
+          release_url=$(curl -s https://api.github.com/repos/terraform-linters/tflint/releases/latest | grep -o -E "https://.+?_Linux_x86_64.zip")
+          echo "Release URL: $release_url"
+          if [ -z "$release_url" ]; then
+            echo "Error: Failed to fetch release URL for TFLint."
+            exit 1
+          fi
+          curl -L "$release_url" -o tflint.zip
           unzip tflint.zip
           sudo mv tflint /usr/local/bin/
           rm tflint.zip
